Controllers/EscuelaController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Platzi_AspNet.Models;

namespace Platzi_AspNet.Controllers
{
    public class EscuelaController: Controller
    {
        public IActionResult Index()
        {
            var escuela = new Escuela();
            escuela.AñoDeCreación=2005;
            escuela.UniqueId= Guid.NewGuid().ToString();
            escuela.Nombre = "School Cacao";
            escuela.Dirección = "Zona 4, 43-2 avenida";
            escuela.Ciudad = "Guatemala";
            escuela.Pais = "Guatemala";
            escuela.TipoEscuela = TiposEscuela.Secundaria;

            ViewBag.CosaDinamica = System.DateTime.Today;
            return View(escuela);
        }
    }
}

Views/Shared/AsignaturaSimple.cshtml
@* @model Asignatura *@

<p>
    Name: @Model.Nombre <br>
    Id: @Model.UniqueId
</p>

Views/Shared/ListaObjetoEscuela.cshtml
@*
@model List<ObjetoEscuelaBase>
*@

<table class="table table-striped">
    <thead class="table table-dark">
    <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Id</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var obj in @Model)
    {
        <tr>
            <td>@obj.Nombre</td>
            <td>@obj.UniqueId</td>
        </tr>
    }
    </tbody>
</table>

Views/Shared/ObjetoEscuelaSimple.cshtml
@model ObjetoEscuelaBase

<p>
    Name: @Model.Nombre <br>
    Id: @Model.UniqueId
</p>

Views/Shared/Simple.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.Net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody();
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.Net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.Net</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Escuela" asp-action="Index">School</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-ligh">
            &copy; 2021 - ASP.Net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>